eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: service-upload
  profiles:
    active: fileupload
  cloud:
    config:
      discovery:
        enable: true
        serviceId: service-zuul

server:
  port: 8040
