version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  web:
    container_name: nginx
    image: hub.c.163.com/library/nginx:latest
    ports:
      - 80:80
    volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       - ../www:/usr/share/nginx/html
  mysql:
    container_name: mysql
    build: ./mysql
#    image: hub.c.163.com/library/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql.conf:/etc/mysql/conf.d/my.conf
      - ./mysql/data:/var/lib/mysql
#      - ../db2/data:/db2data
#    command:
#      - /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
  db2:
#    build: ./db2
    container_name: db2
    image: db297
#    image: ibmcom/db2express-c
#    image: angoca/db2-instance
    tty: true
    privileged: true
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: "!Q1q2w3e4r"
    ports:
      - "50000:50000"
#    command: ["db2start"]
    volumes:
#      - /db2data
      - ./db2/data:/db2data
#      - ~/work/docker_db2:/home/angoca/db2-instance


