version: "3"
services:

  redis:
    image: redis
    ports:
    - 6379:6379

  web:
    container_name: web
    image: hub.c.163.com/library/nginx:latest
    ports:
    - 80:80
#    network_mode: host
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ../www:/usr/share/nginx/html

#  zoo1:
#    image: zookeeper
#    restart: always
#    container_name: zoo1
#    ports:
#      - "2181:2181"
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_SERVERS: server.1=zoo1:2888:3888 #server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

#  tomcat:
#    image: tomcat:7
#    privileged: true
#    volumes:
#      - ./tomcat/www:/usr/local/tomcat/webapps/www
#    ports:
#      - "8090:8080"

  #  container_name: mysql
  #    build: ./mysql
  #    #    image: hub.c.163.com/library/mysql:latest
  #    environment:
  #      MYSQL_ROOT_PASSWORD: 123
  #    ports:
  #    - 3306:3306
  #    volumes:
  #    - ./mysql/mysql.conf:/etc/mysql/conf.d/my.conf
  #    - ./mysql/data:/var/lib/mysql
  #      - ../db2/data:/db2data
  #    command:
  #      - /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
  db2:
    build: ./db2
    container_name: db2
    #    image: db297
    #    image: ibmcom/db2express-c
    #    image: angoca/db2-instance
    #    tty: true
    privileged: true
    #    environment:
    #      LICENSE: accept
    #      DB2INST1_PASSWORD: "!Q1q2w3e4r"
    ports:
    - "50000:50000"
#    command: ["db2start"]
#    volumes:
#      - /db2data
#      - ./db2/data:/db2data
#      - ~/work/docker_db2:/home/angoca/db2-instance

#  fastdfs_tracker:
#    container_name: tracker
#    image: season/fastdfs
#    command: tracker
#    ports:
#      - "22122:22122"
#    volumes:
#      - ./fastdfs/tracker_data:/fastdfs/tracker
#
#  fastdfs_storage0:
#    container_name: storage0
#    image: season/fastdfs
#    command: storage
#    environment:
#      - TRACKER_SERVER=172.19.0.3:22122
#    volumes:
#      - ./fastdfs/storage0:/fastdfs/storage
#    ports:
#      - "23000:23000"
#    links:
#      - fastdfs_tracker



