uploads:
#  type: fastdfs
  type: native
  path: /Users/bin/work/uploads

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
  - 39.104.106.65:22122