#db1:
#  jdbc:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 1q2w3e4r

#upload:
#  path: /Users/bin/work/uploads
#spring.jpa.properties.hibernate.dialect=com.beeasy.hzback.core.helper.MySQL5DialectFK

#权限校验
permission:
  #校验类型, 使用全局授权
  type: global
#  type: local


workflow:
  timeStep: 1
  lockTimeout: 10

mybatis:
  mapperLocations: classpath:hzadmin/src/main/resources/mybatis.mapper/*.xml
  typeAliasesPackage: com.beeasy.hzback.modules.setting.entity

filecloud:
  address: "47.93.54.105"
  username: "admin"
  password: "admin"
  enable: true

  userDefaultPassword: "qwer!@34"

  commonUsername: "admin"
  commonPassword: "admin"
  commonRootId: 1041

#swagger:
#  host: 127.0.0.1:8081


server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /


spring:
    servlet:
      multipart:
        max-file-size: 10Mb
        max-request-size: 10Mb
#    http:
#      multipart:
#        max-file-size: 10Mb
#        max-request-size: 10Mb
#    mvc:
#        view:
#            prefix: /views/
#            suffix: .ftl
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          cache:
            use_query_cache: false
          archive:
            autodetection: false
          dialect: com.beeasy.hzback.core.helper.MySQL5DialectFK



#    freemarker:
#        cache: false
#        request-context-attribute: request

    datasource:
        name: test
#        mysql
        url: jdbc:mysql://0.0.0.0:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
#        password: "!Q1q2w3e4r"
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
#        mysql-end
#        db2
#        url: jdbc:db2://47.96.98.198:50000/sample
#        username: db2inst1
#        password: "!Q1q2w3e4r"
#        driver-class-nodeName: com.ibm.db2.jcc.DB2Driver
#        db2-end
        # 使用druid数据源
        type: org.springframework.jdbc.datasource.DriverManagerDataSource
#        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
       database: 0
       host: 127.0.0.1
       port: 6379
       password:
       timeout: 5000

    session:
        store-type: none




