db1:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1q2w3e4r

mybatis:
  mapperLocations: classpath:hzadmin/src/main/resources/mybatis.mapper/*.xml
  typeAliasesPackage: com.beeasy.hzback.modules.setting.entity

server:
  port: 8070
  context-path: /
  address: 192.168.31.201

spring:
    mvc:
        view:
            prefix: /views/
            suffix: .ftl

    freemarker:
        cache: false
        request-context-attribute: request

    datasource:
        name: test
#        mysql
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
#        mysql-end
#        db2
#        url: jdbc:db2://localhost:50000/sample
#        username: db2admin
#        password: 123
#        driver-class-name: com.ibm.db2.jcc.DB2Driver
#        db2-end
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
           database: 0
           host: 127.0.0.1
           port: 6379
           password:
           timeout: 0
           pool:
               max-active: 8
               max-wait: -1
               max-idle: 8
               min-idle: 0
    session:
        store-type: none



adminMenu:
  -
    title: 系统配置
    children:
      -
        title: 用户管理
        href: /admin/setting/user/list
      -
        title: 部门设置
        href: /admin/setting/department/list

      -
        title: 角色设置
        href: /admin/setting/role/list

      -
        title: 流程配置
        href: /admin/setting/work/list

      -
        title: 业务部署
        href: /admin/setting/workflow/list

      -
        title: 权限配置
        href: /admin/setting/permission/list

  -
    title: 工作台
    children:
      -
        title: 未处理工作
        href:

      -
        title: 已处理工作
        href:

      -
        title: 我的消息
        href: