db1:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1q2w3e4r

mybatis:
  mapperLocations: classpath:hzadmin/src/main/resources/mybatis.mapper/*.xml
  typeAliasesPackage: com.beeasy.hzback.modules.setting.entity


spring:
    mvc:
        view:
            prefix: /views/
            suffix: .ftl

    freemarker:
        cache: false
        request-context-attribute: request

    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
           database: 0
           host: 127.0.0.1
           port: 6379
           password:
           timeout: 0
           pool:
               max-active: 8
               max-wait: -1
               max-idle: 8
               min-idle: 0
    session:
        store-type: none



adminMenu:
  -
    title: 系统配置
    children:
      -
        title: 角色设置
        href:
      -
        title: 部门设置
        href:
      -
        title: 业务设置
        href:
      -
        title: 节点配置
        href:
      -
        title: 流程配置
        href: