#rpc:
#  secret: "1q2w3e4r"
#  url: http://47.94.97.138

dev:
  debug: true

auth:
  url: /api/
  not: /api/login

multipul:
  datasources:
    - name: main
      driver: com.ibm.db2.jcc.DB2Driver
      url: jdbc:db2://47.94.97.138:50000/test
      username: db2inst1
      password: db2inst1
      alias: fzsys_hy
#      name: h2
#        driver: com.ibm.db2.jcc.DB2Driver
#        url: jdbc:db2://47.94.97.138:50000/test
#        username: db2inst2
#        password: db2inst2


filecloud:
  server: http://47.94.97.138/disk
  username: "admin"
  password: "admin"
  userDefaultPassword: "qwer!@34"

  commonUsername: "admin"
  commonPassword: "admin"
  commonRootId: 1041

  wfPid: 0

#swagger:
#  host: 127.0.0.1:8081

beetlsql:
  dbStyle: org.beetl.sql.core.db.DB2SqlStyle

server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /

uploads:
  server: http://localhost
  type: fastdfs
  path: d:/upload
#  temp: /Users/bin/work/uploads/temp
#  avatar: /Users/bin/work/uploads/avatar
#  logs: /Users/bin/work/uploads/logs

#
#fdfs:
#  so-timeout: 1501
#  connect-timeout: 601
#  thumb-image:             #缩略图生成参数
#    width: 150
#    height: 150
#  tracker-list:
#  - 39.104.106.65:22122


spring:
  application:
    name: service-hzback
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

  activemq:
    broker-url: tcp://47.94.97.138:8011?jms.blobTransferPolicy.uploadUrl=http://47.94.97.138:8012/fileserver/

  #  datasource:
#    url: jdbc:sqlite::resource:server/data.db
#    username:
#    password:
#    driver-class-name: org.sqlite.JDBC

#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: com.beeasy.hzback.core.helper.DB2DialectFK

#  datasource:
#    name: test
#    #mysql
#    #    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    #    username: root
#    #        password: "!Q1q2w3e4r"
#    #    password: 123
#    #    driver-class-name: com.mysql.jdbc.Driver
#    #        mysql-end
#    #        db2
#    url: jdbc:db2://47.94.97.138:50000/test
#    username: db2inst1
#    password: db2inst1
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#    #        db2-end
#    # 使用druid数据源
#    type: org.springframework.jdbc.datasource.DriverManagerDataSource
#    #    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#  #      filters: stat
#  #      maxActive: 20
#  #      initialSize: 1
#  #      maxWait: 60000
#  #      minIdle: 1
#  #      timeBetweenEvictionRunsMillis: 60000
#  #      minEvictableIdleTimeMillis: 300000
#        validationQuery: select count(1) from t_user
#  #      testWhileIdle: true
#  #      testOnBorrow: false
#  #      testOnReturn: false
#  #      poolPreparedStatements: true
#  #      maxOpenPreparedStatements: 20


  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms

  session:
    store-type: none

  mvc:
    async:
      request-timeout: 30000ms



filepath:
  path: /home/fzsysafter/app/transformDefinitionFile.xlsx
  whitelistpath: /hz/whitelist



#  dubbo:
#    server: true
#    registry: N/A
#    provider:
#      port: 28001

#jodconverter:
#  enabled: true
#  port-numbers: 8100
#  office-home: /opt/openoffice4
#  max-tasks-per-process: 10

