spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        cache:
          use_query_cache: false
        archive:
          autodetection: false
        dialect: com.beeasy.hzback.core.helper.MySQL5DialectFK

  datasource:
    name: test
    #mysql
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    #        password: "!Q1q2w3e4r"
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    #        mysql-end
    #        db2
    #    url: jdbc:db2://localhost:50000/test
    #    username: db2inst1
    #    password: db2inst1
    #    driver-class-name: com.ibm.db2.jcc.DB2Driver
    #        db2-end
    # 使用druid数据源
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    #    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20