spring:
  datasource:
    name: test
    #mysql
    #    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    username: root
    #        password: "!Q1q2w3e4r"
    #    password: 123
    #    driver-class-name: com.mysql.jdbc.Driver
    #        mysql-end
    #        db2
    url: jdbc:db2://localhost:50000/test
    username: db2inst1
    password: db2inst1
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    #        db2-end


server:
  port: 8089

beetlsql:
  dbStyle: org.beetl.sql.core.db.DB2SqlStyle

